<?php

namespace Vigiroute\ControleBundle\Repository;

/**
 * AffaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffaireRepository extends \Doctrine\ORM\EntityRepository
{
}
