<?php

namespace Vigiroute\ControleBundle\Repository;

/**
 * ContreventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContreventionRepository extends \Doctrine\ORM\EntityRepository
{
}
