<?php

namespace Vigiroute\ControleBundle\Repository;

/**
 * InfoAcidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoAcidentRepository extends \Doctrine\ORM\EntityRepository
{
}
