<?php

namespace Vigiroute\DommageCorporelBundle\Repository;

/**
 * ConstantVehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstantVehiculeRepository extends \Doctrine\ORM\EntityRepository
{
}
