<?php

namespace Vigiroute\DommageCorporelBundle\Repository;

/**
 * DommageCorporelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DommageCorporelRepository extends \Doctrine\ORM\EntityRepository
{
}
