<?php

namespace Vigiroute\DommageCorporelBundle\Repository;

/**
 * GardeAVueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GardeAVueRepository extends \Doctrine\ORM\EntityRepository
{
}
