<?php

namespace Vigiroute\DommageCorporelBundle\Repository;

/**
 * MesureAvantTransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesureAvantTransportRepository extends \Doctrine\ORM\EntityRepository
{
}
