<?php

namespace Vigiroute\DommageCorporelBundle\Repository;

/**
 * OperationCorporelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationCorporelRepository extends \Doctrine\ORM\EntityRepository
{
}
