<?php

namespace Vigiroute\GendarmerieBundle\Repository;

/**
 * BrigadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrigadeRepository extends \Doctrine\ORM\EntityRepository
{
}
