<?php

namespace Vigiroute\GendarmerieBundle\Repository;

/**
 * InfoCommunGendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoCommunGendRepository extends \Doctrine\ORM\EntityRepository
{
}
