<?php

namespace Vigiroute\GendarmerieBundle\Repository;

/**
 * LegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegionRepository extends \Doctrine\ORM\EntityRepository
{
}
