<?php

namespace Vigiroute\DommageMaterielBundle\Repository;

/**
 * CaractereRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaractereRouteRepository extends \Doctrine\ORM\EntityRepository
{
}
