<?php

namespace Vigiroute\DommageMaterielBundle\Repository;

/**
 * CirconstanceAccidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CirconstanceAccidentRepository extends \Doctrine\ORM\EntityRepository
{
}
