<?php

namespace Vigiroute\DommageMaterielBundle\Repository;

/**
 * DommageMaterielsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DommageMaterielsRepository extends \Doctrine\ORM\EntityRepository
{
}
