<?php

namespace Vigiroute\DommageMaterielBundle\Repository;

/**
 * pietonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pietonRepository extends \Doctrine\ORM\EntityRepository
{
}
