<?php

namespace Vigiroute\DommageMaterielBundle\Repository;

/**
 * UsagerVehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsagerVehiculeRepository extends \Doctrine\ORM\EntityRepository
{
}
