<?php

namespace Vigiroute\GeographieBundle\Repository;

/**
 * InfoLocaliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoLocaliteRepository extends \Doctrine\ORM\EntityRepository
{
}
