<?php

namespace Vigiroute\EquipementBundle\Repository;

/**
 * BraceletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BraceletRepository extends \Doctrine\ORM\EntityRepository
{
}
