<?php

namespace Vigiroute\EquipementBundle\Repository;

/**
 * OutilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutilRepository extends \Doctrine\ORM\EntityRepository
{
}
