<?php

namespace Vigiroute\EquipementBundle\Repository;

/**
 * TerminalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerminalRepository extends \Doctrine\ORM\EntityRepository
{
}
