<?php

namespace Vigiroute\EquipementBundle\Repository;

/**
 * WebcamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebcamRepository extends \Doctrine\ORM\EntityRepository
{
}
